module.exports = {
  brew: [
    "ack",
    "ag",
    "bat",
    "coreutils",
    "delta",
    "dos2unix",
    "dpkg",
    "exa",
    "findutils",
    "fortune",
    "fselect",
    "fzf",
    "readline",
    "gawk",
    "gifsicle",
    "gnupg",
    "gnu-sed --with-default-names",
    "grep --with-default-names",
    "homebrew/dupes/grep",
    "httpie",
    "jq",
    "mas",
    "mongodb-community",
    "moreutils",
    "mysql",
    "neofetch",
    "nmap",
    "openconnect",
    "python",
    "reattach-to-user-namespace",
    "srkomodo/tap/shadowfox-updater",
    "homebrew/dupes/screen",
    "spicetify-cli",
    "spotify-tui",
    "spotifyd",
    "tldr",
    "tmux",
    "todo-txt",
    "tree",
    "ttyrec",
    "vim --with-client-server --with-override-system-vi",
    "watch",
    "wget --enable-iri",
    "youtube-dl",
  ],
  cask: [
    "adobe-creative-cloud",
    "aerial",
    "altserver",
    "android-file-transfer",
    "android-platform-tools",
    "android-studio",
    "arduino",
    "autodesk-fusion360",
    "balenaetcher",
    "barrier",
    "caprine",
    "checkra1n",
    "coconutbattery",
    "darwindumper",
    "discord",
    "firefox",
    "flux",
    "fritzing",
    "github",
    "google-backup-and-sync",
    "google-chrome",
    "hackintool",
    "iina",
    "intel-power-gadget",
    "iterm2",
    "java",
    "karabiner-elements",
    "keka",
    "macupdater",
    "mamp",
    "mongodb-compass",
    "monitorcontrol",
    "mos",
    "mysqlworkbench",
    "open-in-code",
    "sketchup",
    "spotify",
    "surfshark",
    "teamviewer",
    "telegram",
    "transmission",
    "tunnelblick",
    "ukelele",
    "ultimaker-cura",
    "virtualbox",
    "virtualbox-extension-pack",
    "visual-studio-code",
    "vlc",
  ],
  gem: ["colorls"],
  mas: [
    // Microsoft Remote Desktop
    "1295203466",
    // Paste
    "967805235",
    // Trello
    "1278508951",
    // Magnet
    "441258766",
    // LastPass
    "926036361",
    // Spark
    "1176895641",
    // Twitter
    "1482454543",
  ],
  npm: [
    "antic",
    "buzzphrase",
    "eslint",
    "instant-markdown-d",
    "gulp-cli",
    "npm-check-updates",
    "prettier",
    "prettyjson",
    "trash",
    "vtop",
    "webtorrent-cli",
  ],
};
